name: Crawler

on:
  schedule:
    - cron: '30 15 * * *'
  workflow_dispatch:

jobs:
  crawler:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set current day of month as env variable
        env:
          TZ: 'Asia/Tokyo'
        run: |
          echo "CURRENT_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
          echo "YESTERDAY_DATE=$(date '+%Y-%m-%d' --date '1 day ago')" >> $GITHUB_ENV

      - name: Install dependencies
        run: | 
          cd crawler
          npm install
          node crawler.js --from ${{ env.YESTERDAY_DATE }} --to ${{ env.CURRENT_DATE }} --user hirasawa
          git config --local user.name "Action Bot"
          git config --local user.email "actionBot@example.com"
          git add .
          git commit -m "POST: ${{ env.YESTERDAY_DATE }}"

      - name: Deploy
        uses: ad-m/github-push-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
